name: E2E

on:
    pull_request: null
    push:
        branches:
            - main
            - master

jobs:
    laravel_test:
        name: Test in a Laravel project
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: "8.2"
                    extensions: mbstring
                    coverage: none

            -   uses: ramsey/composer-install@v3

            -   run: tests/laravel-test.sh
